# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_authors_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='descripton',
            new_name='description',
        ),
    ]
